language: php

sudo: false

php:
  - 7.3

matrix:
  fast_finish: true

install:
  - composer install
  - composer require php-coveralls/php-coveralls

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
